// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3rad4ZIVhRZXp-O1KEQEgfQqReZn9U6E',
    appId: '1:800996248675:web:6b5734753b075d01297c56',
    messagingSenderId: '800996248675',
    projectId: 'telodigoapp-40501',
    authDomain: 'telodigoapp-40501.firebaseapp.com',
    storageBucket: 'telodigoapp-40501.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCROcmt0iCPQNXXLuM0Td_AiRsq6hwLqzw',
    appId: '1:800996248675:android:4e4911e5c95d5d8c297c56',
    messagingSenderId: '800996248675',
    projectId: 'telodigoapp-40501',
    storageBucket: 'telodigoapp-40501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByOP7JRNB4fhKQE2O-mIn2hXpP5V0LB7I',
    appId: '1:800996248675:ios:4c66cc741149c7b9297c56',
    messagingSenderId: '800996248675',
    projectId: 'telodigoapp-40501',
    storageBucket: 'telodigoapp-40501.appspot.com',
    iosBundleId: 'com.lessynthon.telodigo.telodigo',
  );
}
